[changelog]
body = """
## 插件更新
> [!NOTE]
> 当前版本：`{% if version %}({{ version }}){%- endif -%}`
{% for group, commits in commits | group_by(attribute="group") %}
{% if group != "✨ 新亮点" %}
<details>
<summary><h3>{{ group | upper_first }}</h3></summary>
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}\
  {% if commit.remote.username %} 作者: @{{ commit.remote.username }}{%- endif -%}
{% endfor %}
</details>
{% else %}
### {{ group | upper_first }}
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}\
  {% if commit.remote.username %} 作者: @{{ commit.remote.username }}{%- endif -%}
{% endfor %}
{% endif %}
{% endfor -%}
{% if version %}
  {% if previous.version %}
**完整 Changelog**: 版本对比 {{ previous.version }} → {{ version }}
  {% endif %}
{% else -%}
  {% raw %}
{% endraw %}
{% endif %}
"""
trim = true
footer = "<!-- generated by git-cliff -->"
output = "CHANGELOG.md"

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "✨ 新亮点"},
    { message = "^fix", group = "🛠️ 修复的问题"},
    { message = "^refactor", group = "🔃 功能重构"},
    { message = "^docs", group = "📄 文档更新"},
    { message = "^style", group = "🏞️ 样式优化"},
]
protect_breaking_commits = false
filter_commits = true
topo_order = false
sort_commits = "oldest"
link_parsers = []
